### ISSUE TITLE
Github links at bottom of place page do not load file number

### ISSUE THREAD

**Issue by davidamichelson** [srophe/places#6] opened 2013-11-07 02:32 UTC
For some reason, the TEi link on place 78 html page works in the upper corner but not in the see also list where it resolves to: https://github.com/srophe/places/blob/master/xml/.xml

Thanks!
Dave

**Comment by tacarlson** [comment] 2013-11-07 02:46
This is a duplicate of srophe/srp-places-app#120 .

**Comment by wsalesky** [comment] 2013-11-07 20:42
Is this something you would like fixed now, or in the new version?

**Comment by davidamichelson** [comment] 2013-11-07 21:32
No it can wait for the new version. Sorry for not realizing it already had
a ticket.

**Comment by wsalesky** [comment] 2020-02-14 17:30
@davidamichelson stale issue.

**Closed as completed by wsalesky** 2020-02-14 17:30 UTC
